# Generated by Django 3.0.5 on 2020-05-03 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=uuid.UUID('f2b9a60c-891f-4c7b-b74f-b300918f179c'), max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('Role', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=16)),
            ],
        ),
    ]
