# Generated by Django 3.0.5 on 2020-05-29 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='user_id',
            field=models.CharField(default=uuid.UUID('6e9e44ea-f103-4133-83c7-c8f36ab8f622'), max_length=40, unique=True),
        ),
    ]
