# Generated by Django 3.0.5 on 2020-05-29 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200529_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='user_id',
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_id',
            field=models.CharField(default=uuid.UUID('9b872dfd-a472-49a6-9cf6-7de2f6ccff39'), max_length=40, unique=True),
        ),
    ]
