# Generated by Django 3.0.7 on 2020-06-10 12:47

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200529_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_hired',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_id',
            field=models.CharField(default=uuid.UUID('67e8553e-8046-4a47-a833-2330592aac9c'), max_length=40, unique=True),
        ),
    ]
