# Generated by Django 3.0.7 on 2020-06-10 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200610_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_id',
            field=models.CharField(default=uuid.UUID('cc72596b-28dd-49ae-a867-b8fcaedf730d'), max_length=40, unique=True),
        ),
    ]
